USE spring_blog_db;

insert into posts (title, body) values ('Southern boubou', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into posts (title, body) values ('Gaur', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into posts (title, body) values ('Two-toed sloth', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into posts (title, body) values ('Puffin, horned', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into posts (title, body) values ('Crane, black-crowned', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into posts (title, body) values ('Blue-breasted cordon bleu', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into posts (title, body) values ('Blue wildebeest', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into posts (title, body) values ('Brazilian otter', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into posts (title, body) values ('Wild turkey', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into posts (title, body) values ('Levaillant''s barbet', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into posts (title, body) values ('Legaan, water', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into posts (title, body) values ('Rainbow lory', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into posts (title, body) values ('Owl, madagascar hawk', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into posts (title, body) values ('Mexican wolf', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into posts (title, body) values ('American alligator', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into posts (title, body) values ('Kingfisher, pied', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into posts (title, body) values ('Tamandua, southern', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into posts (title, body) values ('Nine-banded armadillo', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into posts (title, body) values ('Long-tailed skua', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into posts (title, body) values ('Turtle (unidentified)', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into posts (title, body) values ('Squirrel, red', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into posts (title, body) values ('Whale, long-finned pilot', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into posts (title, body) values ('Cat, toddy', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into posts (title, body) values ('Meerkat, red', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into posts (title, body) values ('Monitor, two-banded', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into posts (title, body) values ('Monkey, bleeding heart', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into posts (title, body) values ('Harbor seal', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into posts (title, body) values ('Dog, raccoon', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into posts (title, body) values ('Lemur, lesser mouse', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into posts (title, body) values ('Whale, baleen', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into posts (title, body) values ('Lizard, giant girdled', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into posts (title, body) values ('Waterbuck, common', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into posts (title, body) values ('Serval', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into posts (title, body) values ('Deer, swamp', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into posts (title, body) values ('Impala', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into posts (title, body) values ('Red-necked phalarope', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into posts (title, body) values ('Long-billed cockatoo', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into posts (title, body) values ('Snake, eastern indigo', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into posts (title, body) values ('Monitor lizard (unidentified)', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into posts (title, body) values ('Common seal', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into posts (title, body) values ('Javanese cormorant', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into posts (title, body) values ('Blue peacock', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into posts (title, body) values ('Glider, squirrel', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into posts (title, body) values ('Trumpeter, green-winged', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into posts (title, body) values ('Flightless cormorant', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into posts (title, body) values ('European red squirrel', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into posts (title, body) values ('Gonolek, burchell''s', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into posts (title, body) values ('Springbok', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into posts (title, body) values ('Superb starling', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into posts (title, body) values ('Lemming, collared', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
